/* Generated document. DO NOT CHANGE */

NSString * const EXERCISE_SEGUE = @"EXERCISE_SEGUE";
NSString * const WEEK_DAY_SEGUE = @"WEEK_DAY_SEGUE";

NSString * const DAY_DETAIL_TABLE_VIEW_CONTROLLER = @"DAY_DETAIL_TABLE_VIEW_CONTROLLER";
NSString * const EXERCISE_DETAIL_VIEW_CONTROLLER = @"EXERCISE_DETAIL_VIEW_CONTROLLER";
NSString * const PROFILE_NAV_CONTROLLER = @"PROFILE_NAV_CONTROLLER";
NSString * const PROFILE_VIEW_CONTROLLER = @"PROFILE_VIEW_CONTROLLER";
NSString * const SCHEDULE_NAV_CONTROLLER = @"SCHEDULE_NAV_CONTROLLER";
NSString * const SCHEDULE_VIEW_CONTROLLER = @"SCHEDULE_VIEW_CONTROLLER";
